Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "copyright", "credits" or "license()" for more information.
>>> 
===== RESTART: /home/student/rakan19_lab5/meet2017y1lab5/add_numbers.py =====
>>> add_numbers(1,5)
15
>>> add_numbers(1000, 1500)
626250
>>> add_numbers(333,777)
246975
>>> 
===== RESTART: /home/student/rakan19_lab5/meet2017y1lab5/add_numbers.py =====
>>> add_number(1,%)
SyntaxError: invalid syntax
>>> 
===== RESTART: /home/student/rakan19_lab5/meet2017y1lab5/add_numbers.py =====
>>> add_numbers(333,777)
246975
>>> 
========= RESTART: /home/student/rakan19_lab5/meet2017y1lab5/fun2.py =========
*
*
*
*
*
>>> 
========= RESTART: /home/student/rakan19_lab5/meet2017y1lab5/fun2.py =========
*****
>>> 
===== RESTART: /home/student/rakan19_lab5/meet2017y1lab5/add_numbers.py =====
>>> add_numbers(1, 5)
>>> 
========= RESTART: /home/student/rakan19_lab5/meet2017y1lab5/fun2.py =========
>>> draw_1d(3)
***
>>> 
========= RESTART: /home/student/rakan19_lab5/meet2017y1lab5/fun2.py =========
>>> draw_1d(1000,rakan)
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    draw_1d(1000,rakan)
NameError: name 'rakan' is not defined
>>> draw_1d(1000,'rakan')
rakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakanrakan
>>> 
